nelmio_api_doc:
    use_validation_groups: true
    documentation:
        info:
            title: Tic Tac Toe API
            description: This is an awesome homework for nerds
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
#        host_patterns: # document only routes with a host of the form api.*
#            - ^api\.